version: 2
jobs:
  checks:
    docker:
      - image: circleci/node:10.15

    working_directory: ~/repo

    steps:
      - add_ssh_keys:
          fingerprints:
            - '6a:78:0f:2d:57:a2:d1:83:1a:81:4e:af:76:d1:ff:31'

      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Lint files
          command: yarn lint

      - run:
          name: Check types
          command: yarn tsc

      - run:
          name: Run tests
          command: yarn test

  publish:
    docker:
      - image: circleci/node:10.15

    steps:
      - run:
          name: Create builds
          command: yarn build

      - run:
          name: Publish new version
          command: yarn release

workflows:
  version: 2
  workflow:
    jobs:
      - checks
      - publish:
          requires:
            - checks
          filters:
            branches:
              only: master
